In [57]:
import psycopg
import pandas as pd

In [58]:
conn = psycopg.connect("postgresql://root@localhost:26257", application_name="$ docs_simplecrud_psycopg3")

In [59]:
df = pd.read_csv('listings.csv.gz', compression='gzip')

In [60]:
df.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 75, dtype: object

In [61]:
def get_column_and_type(dfparam):    
    
    dtypedict = {}
    for i,j in zip(dfparam.columns, dfparam.dtypes):
        if "object" in str(j):
            dtypedict.update({i: "TEXT"})
                                 
        if "datetime" in str(j):
            dtypedict.update({i: "TIMESTAMP"})

        if "float" in str(j):
            dtypedict.update({i: "FLOAT"})

        if "int" in str(j):
            dtypedict.update({i: "INTEGER"})
        
    return dtypedict

In [62]:
columns = get_column_and_type(df)

In [63]:
def create_table_statement(table_name, columns):
    sql = f"CREATE TABLE {table_name} ("

    for column_name, data_type in columns.items():
        sql += f"{column_name} {data_type}, "
    
    sql = sql.rstrip(', ')
    sql += ');'

    return sql

In [64]:
table_name = 'listings'

In [65]:
with conn.cursor() as cur:
    cur.execute(create_table_statement(table_name, columns))
conn.commit()

InvalidName: no database or schema specified

In [ ]:
with conn.cursor() as cur:
    df = pd.read_sql('SELECT * FROM listings', conn)
conn.commit()

df

/tmp/ipykernel_1193/685995424.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT * FROM listings', conn)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,47828453,https://www.airbnb.com/rooms/47828453,20240106043908,2024-01-06,city scrape,Rental unit in Albany · ★4.40 · 2 bedrooms · 3...,None,None,https://a0.muscache.com/pictures/47b30ae3-42bc...,299638115,...,4.73,4.20,4.27,None,f,3,3,0,0,0.42
1,13711253,https://www.airbnb.com/rooms/13711253,20240106043908,2024-01-06,city scrape,Home in Albany · ★4.77 · 1 bedroom · 1 bed · 1...,None,2 block away from Honest Weight Co Op organic ...,https://a0.muscache.com/pictures/0dfbddb7-b6eb...,61700428,...,4.97,4.63,4.82,None,f,3,0,3,0,2.45
2,684100173908872919,https://www.airbnb.com/rooms/684100173908872919,20240106043908,2024-01-06,city scrape,Condo in Albany · ★4.40 · 1 bedroom · 2 beds ·...,None,None,https://a0.muscache.com/pictures/dad915ce-0619...,1176120,...,4.79,4.10,4.41,None,f,3,3,0,0,4.20
3,48124042,https://www.airbnb.com/rooms/48124042,20240106043908,2024-01-06,city scrape,Rental unit in Albany · ★4.89 · 2 bedrooms · 3...,None,Downtown Albany - Corner of North Pearl and Ma...,https://a0.muscache.com/pictures/miso/Hosting-...,385664127,...,4.93,4.89,4.86,None,f,2,2,0,0,5.54
4,588298411730694861,https://www.airbnb.com/rooms/588298411730694861,20240106043908,2024-01-06,city scrape,Rental unit in Albany · ★5.0 · 1 bedroom · 1 b...,None,None,https://a0.muscache.com/pictures/b93dc43c-6bd4...,353498132,...,5.00,4.56,5.00,None,f,5,5,0,0,0.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,593272120497643087,https://www.airbnb.com/rooms/593272120497643087,20240106043908,2024-01-06,city scrape,Home in Albany · ★4.99 · 1 bedroom · 2 beds · ...,None,Albany safest and most walkable.,https://a0.muscache.com/pictures/miso/Hosting-...,382970529,...,4.99,4.96,4.96,None,f,10,1,9,0,4.14
406,24120690,https://www.airbnb.com/rooms/24120690,20240106043908,2024-01-06,city scrape,Guest suite in Albany · ★4.93 · 1 bedroom · 1 ...,None,This is a walking neighborhood and very safe.,https://a0.muscache.com/pictures/5179cbd1-f087...,156446839,...,4.97,4.97,4.97,None,f,1,0,1,0,1.67
407,737574278276037589,https://www.airbnb.com/rooms/737574278276037589,20240106043908,2024-01-06,city scrape,Rental unit in Albany · ★4.72 · 4 bedrooms · 4...,None,"Minutes to St Rose, St Peters <br />street is ...",https://a0.muscache.com/pictures/bd6b3f67-f8d5...,232967878,...,4.91,4.53,4.69,None,f,19,19,0,0,2.21
408,47440071,https://www.airbnb.com/rooms/47440071,20240106043908,2024-01-06,city scrape,Home in Albany · ★4.96 · 1 bedroom · 1 bed · 1...,None,"Very walkable. Movie Theatre, Grocery, and sev...",https://a0.muscache.com/pictures/9d8bd06d-9494...,382970529,...,4.99,4.97,4.99,None,f,10,1,9,0,3.13
409,870457209918967324,https://www.airbnb.com/rooms/870457209918967324,20240106043908,2024-01-06,city scrape,Home in Albany · 1 bedroom · 1 bed · 1 private...,None,None,https://a0.muscache.com/pictures/miso/Hosting-...,177073982,...,5.00,5.00,5.00,None,f,2,0,2,0,0.31

In [66]:
with conn.cursor() as cur:
    cur.execute("""CREATE TABLE users ( 
        id UUID PRIMARY KEY,
        city STRING,
        name STRING,
        address STRING,
        credit_card STRING,
        dl STRING
        );""")
    
conn.commit()

SyntaxError: at or near "/": syntax error
DETAIL:  source SQL:
CREATE TABLE users (
        id UUID PRIMARY KEY,/
                            ^
HINT:  try \h CREATE TABLE